config/routes.rb
Rails.application.routes.draw do
  get 'health_check/index'
  devise_for :admins, controllers:{ 
    registrations: 'admins/registrations',
    sessions: 'admins/sessions' 
  }
  devise_scope :admin do
    post 'admin/guest_sign_in', to: 'admins/sessions#guest_sign_in'
  end

  devise_for :drivers, controllers:{ 
    registrations: 'drivers/registrations',
    sessions: 'drivers/sessions' 
  }
  devise_scope :driver do
    post 'driver/guest_sign_in', to: 'drivers/sessions#guest_sign_in'
  end

  devise_for :sponsors, controllers:{ 
    registrations: 'sponsors/registrations',
    sessions: 'sponsors/sessions' }
  devise_scope :sponsor do
    post 'sponsor/guest_sign_in', to: 'sponsors/sessions#guest_sign_in'
  end

  root 'homes#index'
  resources :homes, only: %i[ index ] do
    collection do
      get :about
    end
  end

  resources :drivers, only: %i[ index show edit update ] do
    member do
      get :dashboard
      get :followings, :followers
    end
    resources :car_infos, only: %i[ index create edit update destroy ]
    resources :transfer_infos, only: %i[ index create edit update destroy ]
  end

  resources :sponsors, only: %i[ index show edit update ] do
    member do
      get :dashboard
      get :followings, :followers
    end
    scope module: :sponsors do
      resources :advertisements
    end
  end

  resources :under_deals, only: %i[ index show create edit update ] do
    member do
      get :show_driver
    end
    resources :deal_messages, only: %i[ create ]
  end
  scope module: :under_deals do
      get :coming_soon
	end

  resources :infos

  resources :admins, only: %i[ index ]
    namespace :admins do
      resources :sponsors, only: %i[ index show update ]
      resources :drivers, only: %i[ index show update ]
      resources :genres, only: %i[ index create edit update destroy ]
      resources :contacts, only: %i[ index show ]
    end

  resources :contacts, only: %i[ index new create show update ] do
    collection do
      post :confirm
    end
  end
  scope module: :contacts do
    get :new_inquiry
    get :working_inquiry
    get :past_inquiry
  end

  resources :advertisements, only: %i[ index show ] do
    resources :chats, only: %i[ index create ]
    resources :rooms, only: %i[ index show create ]
    member do
      get :genre_index
      get :favorite_index
    end
    resource :favorites, only: %i[ create destroy ]
  end

  post 'relationship_drivers/:sponsor_id', to: 'relationship_drivers#create', as:'relationship_drivers'
  delete 'relationship_drivers/:sponsor_id', to: 'relationship_drivers#destroy'
  
  post '/relationships/:driver_id',to: 'relationships#create',as:'relationships'
  delete '/relationships/:driver_id',to: 'relationships#destroy'
end

app/models/under_deal.rb
class UnderDeal < ApplicationRecord
  belongs_to :driver
	belongs_to :advertisement
	has_one :deal_detail
	accepts_nested_attributes_for :deal_detail, update_only: true

	has_many :deal_messages

	validates :agreement, acceptance: { allow_nil: false, on: :updata }

	enum work_status: {approval_pending: 0, refuse: 1, waiting_kit: 2, sent_kit: 3, advertising: 4, completed: 5, transferred: 6, rated: 7, finished: 8, checked_refuse: 9 }
	# 0="承認待ち", 1="広告キット待ち", 2＝"お断り", 3="キット発送済み" 4="広告作業中", 5="作業完了",  6="振り込み済み", 7=”評価済み”, 8="終了", 9="お断り確認済み"

	has_one_attached :installation_image
end

app/controllers/under_deals_controller.rb
class UnderDealsController < ApplicationController

  def index
    @under_deals = UnderDeal.includes(:advertisement).where(advertisements: {sponsor_id: current_sponsor})
    @finish_deals = UnderDeal.includes(:advertisement, :deal_messages, :driver).references(:advertisement, :deal_messages, :driver).where(work_status: 'finished')
  end

  def show
    @under_deal = UnderDeal.includes(:advertisement, :driver, :deal_detail).includes(advertisement: :sponsor).find(params[:id])
    @advertisement = @under_deal.advertisement
    @deal_messages = @under_deal.deal_messages
    @deal_message = DealMessage.new()
    @deal_detail = DealDetail.new(deal_detail_params)
  end

  def show_driver
    @under_deal = UnderDeal.includes(advertisement: :sponsor).find(params[:id])
    @advertisement = @under_deal.advertisement
    @deal_messages = @under_deal.deal_messages
    @deal_detail = DealDetail.new(deal_detail_params)
  end

  def create
    @under_deal = UnderDeal.new(under_deal_params)
    if @under_deal.save
      redirect_to dashboard_driver_path(current_driver)
    else
      redirect_back(fallback_location: advertisements_path)
    end
  end

  def update
    @under_deal = UnderDeal.find(params[:id])
    if params[:accept]
      @under_deal.work_status = 'waiting_kit'
      @under_deal.save
      redirect_back(fallback_location: under_deal_path(@under_deal))
    elsif params[:refuse]
      @under_deal.work_status = 'refuse'
      @under_deal.save
      redirect_back(fallback_location: under_deal_path(@under_deal))
    elsif params[:sent_kit]
      @under_deal.work_status = 'sent_kit'
      @under_deal.save
      redirect_back(fallback_location: under_deal_path(@under_deal))
    elsif params[:advertising]
      if params[:under_deal]
        @under_deal.work_status = 'advertising'
        @under_deal.update(under_deal_params)
        redirect_back(fallback_location: under_deal_path(@under_deal))
      else
        redirect_back(fallback_location: under_deal_path(@under_deal), alert: '画像が登録されてません')
      end
    elsif params[:completed]
      @deal_detail = DealDetail.new(deal_detail_params)
      @transfer_info = TransferInfo.find(params[:detail][:transfer_info_id])
      @deal_detail.under_deal_id = @under_deal.id
      @deal_detail.bank_name = @transfer_info.bank_name
      @deal_detail.branch_name = @transfer_info.branch_name
      @deal_detail.account_type = @transfer_info.account_type
      @deal_detail.account_number = @transfer_info.account_number
      @deal_detail.account_name = @transfer_info.account_name
      if @deal_detail.save
        @under_deal.work_status = 'completed'
        @under_deal.save
        redirect_back(fallback_location: under_deal_path(@under_deal))
      else
        redirect_back(fallback_location: under_deal_path(@under_deal))
      end
    elsif params[:transferred]
      @under_deal.work_status = 'transferred'
      @under_deal.save
      @deal_detail = @under_deal.deal_detail
      @deal_detail.transfer_status = 'transferred'
      @advertisement = UnderDeal.includes(:advertisement).find(params[:id])
      @deal_detail.payment_amount = @advertisement.advertisement.amounts
      @deal_detail.update(deal_detail_params)
      redirect_back(fallback_location: under_deal_path(@under_deal))
    elsif params[:rated]
      @under_deal.work_status = 'rated'
      @under_deal.save
      @deal_detail = @under_deal.deal_detail
      @deal_detail.transfer_status = 'checked'
      @deal_detail.update(deal_detail_params)
      redirect_back(fallback_location: under_deal_path(@under_deal))
    elsif params[:finished]
      @under_deal.work_status = 'finished'
      @under_deal.save
      redirect_back(fallback_location: under_deal_path(@under_deal))
    elsif params[:checked_refuse]
      @under_deal.work_status = 'checked_refuse'
      @under_deal.save
      redirect_to advertisements_path
    end
  end

  def coming_soon
  end

  private

  def under_deal_params
    params.require(:under_deal).permit(:advertisement_id, :driver_id, :work_status, :installation_image, :agreement)
  end

  def deal_message_params
    params.require(:deal_message).permit(:message, :user_type, :under_deal_id)
  end

  def deal_detail_params
    params.permit(:transfer_status, :bank_name, :branch_name, :account_type, :account_number, :account_name)
  end
end

app/helpers/under_deals_helper.rb
module UnderDealsHelper
	def check_apply
		current_driver.under_deals.where.not(work_status: 'finished').where.not(work_status: 'checked_refuse')
	end

	def full_info_with_newlines(transfer_info)
		"#{transfer_info.bank_name}\n#{transfer_info.account_number}"
	end
end

app/views/under_deals/_advertisement_info.html.erb
<div class="ui grid">
  <div class="row" id="deal-ad-area">
    <div class="five wide column">
      <%= image_tag advertisement.image.variant(resize_to_fill: [200, 200]), class: "ui rounded image" %>
    </div>
    <div class="two wide column"></div>
    <div class="nine wide column">
      <table class="ui definition table">
          <tr>
            <td><span class="tag">広告タイトル</span></td>
            <td><%= advertisement.title %></td>
            <td></td>
          </tr>
          <tr>
            <td><span class="tag">広告見出し</span></td>
            <td><%= advertisement.heading %></td>
            <td></td>
          </tr>
          <tr>
            <td><span class="tag">広告料金</span></td>
            <td><%= converting_to_jpy(advertisement.amounts) %></td>
            <td></td>
          </tr>
          <tr>
            <td><span class="tag">スポンサー名</span></td>
            <td><%= advertisement.sponsor.company_name %></td>
            <td></td>
          </tr>
          <tr>
            <td><span class="tag">広告期間</span></td>
            <td colspan="2"><%= advertisement.start_due_on %> 〜 <%= advertisement.end_due_on %></td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/under_deals/_apply_advertisement.html.erb
<% if driver_signed_in? %>
  <% if check_apply.present? %>
    <div class="ui message">現在、お申し込み中の広告があるため、新規のお申し込みはできません。</div>
  <% else %>
    <%= form_with(model: under_deal, url: under_deals_path, method: :post, class: "ui form") do |f| %>
      <%= f.hidden_field :advertisement_id, value: advertisement.id %>
      <%= f.hidden_field :driver_id, value: current_driver.id %>
      <%= f.submit "この広告に申し込む", class: "ui primary button" %>
    <% end %>
  <% end %>
  <br>
  <section class="question">
    <% if room.nil? %>
      <%= link_to '広告のことで質問する', coming_soon_path, class: "ui teal button" %>
    <% else %>
      <%= link_to '広告のことで質問する', coming_soon_path, class: "ui teal button" %>
    <% end %>
  </section>
  <br>
<% end %>

app/views/under_deals/_flow_driver.html.erb
<% if under_deal.work_status == 'approval_pending' %>
  <div class="ui stackable grid">
    <div class="wide column">
      <div class="ui success big message" style="text-align: center;">
        <h3>お申し込みが完了しました！</h3>
        <h4>スポンサーの承認待ちです。<br>何か質問があったら、メッセージしてみよう</h4>
      </div>
    </div>
  </div>
<% end %>

<% if under_deal.work_status == 'refuse'%>
  <div class="ui stackable grid">
    <div class="wide column">
      <div class="ui negative big message" style="text-align: center;">
        <h3>誠に残念ですが、こちらのお申し込みはスポンサーから承認されませんでした。<br>別の広告を探してみましょう！</h3>
        <%= form_with(model: under_deal, local: true, url: under_deal_path(under_deal), method: :patch, class: "ui form") do |f| %>
          <%= f.submit "了承して、別の広告を探す", name: 'checked_refuse', class: "ui primary button" %>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

<% if under_deal.work_status == 'waiting_kit'%>
  <div class="ui stackable grid">
    <div class="wide column">
      <div class="ui success big message" style="text-align: center;">
        <h3>おめでとうございます！<br>お申し込みが承認されました</h3>
        <h4>広告キットの発送準備中です。<br>発送後、スポンサーから連絡が入ります。<br>今しばらくお待ちください。</h4>
      </div>
    </div>
  </div>
<% end %>

<% if under_deal.work_status == 'sent_kit'%>
  <div class="ui stackable grid">
    <div class="wide column">
      <div class="ui success big message" style="text-align: center;">
        <h3>広告キットが発送されました！</h3>
        <h4>到着後、お車へ設置をお願いします。設置完了後、証明写真を送ってください。</h4>
        <h5><%= link_to "広告キットの取り付けについて", coming_soon_path %></h5>
      </div>
    </div>
  </div>
  <%= render 'under_deals/report_driver', under_deal: under_deal %>
<% end %>

<% if under_deal.work_status == 'advertising'%>
  <div class="ui stackable grid">
    <div class="wide column">
      <div class="ui success big message" style="text-align: center;">
        <h3>準備完了です！</h3>
        <h4>広告作業をしながらドライブを楽しみましょう。<br>広告作業が完了したら、作業完了の報告を送ってください。</h4>
      </div>
    </div>
  </div>
  <%= render 'under_deals/report_driver', { under_deal: under_deal, deal_detail: deal_detail, driver: driver} %>
<% end %>

<% if under_deal.work_status == 'completed'%>
  <div class="ui stackable grid">
    <div class="wide column">
      <div class="ui success big message" style="text-align: center;">
        <h3>お疲れ様でした！</h3>
        <h4>広告作業代の振り込み完了後、スポンサーから連絡が入ります。最後に評価をして広告作業を完了してください。</h4>
      </div>
    </div>
  </div>
  <%= render 'under_deals/report_driver', under_deal: under_deal %>
<% end %>

<% if under_deal.work_status == 'transferred'%>
  <div class="ui stackable grid">
    <div class="wide column">
      <div class="ui success big message" style="text-align: center;">
        <h3>振り込み完了の連絡が来ました！</h3>
        <h4>入金確認をしたら、最後に評価をして広告作業を完了してください。</h4>
      </div>
    </div>
  </div>
  <%= render 'under_deals/report_driver', { under_deal: under_deal, deal_detail: deal_detail } %>
<% end %>

<% if under_deal.work_status == 'rated'%>
  <div class="ui stackable grid">
    <div class="wide column">
      <div class="ui success big message" style="text-align: center;">
        <h3>お疲れ様でした。<br>次の広告を探しにいきましょう！</h3>
      </div>
    </div>
  </div>
  <%= render 'under_deals/report_driver', under_deal: under_deal %>
<% end %>

<% if under_deal.work_status == 'finished'%>
  <div class="ui stackable grid">
    <div class="wide column">
      <div class="ui success big message" style="text-align: center;">
        <h3>この取引きは完了しています。<br>次の広告を探しにいきましょう！</h3>
      </div>
    </div>
  </div>
  <%= render 'under_deals/report_driver', under_deal: under_deal %>
<% end %>

app/views/under_deals/_flow_sponsor.html.erb
<% if under_deal.work_status == 'approval_pending' %>
  <div class="ui stackable grid">
    <div class="wide column">
      <div class="ui success big message" style="text-align: center;">
        <h3>広告に応募がありました!</h3>
      </div>
      <div id="report-driver">
        <%= render 'drivers/profile', driver: under_deal.driver %>
        <p><%= link_to "プロフィールを確認する", driver_path(under_deal.driver.id), name: 'driver_check', class: "ui green button" %></p>
        <p>取引承認待ちです。こちらのドライバーと広告契約を結びますか？</p>
        <%= form_with(model: under_deal, local: true, url: under_deal_path(under_deal), method: :patch, class: "ui form") do |f| %>
          <%= f.submit "広告を依頼する", name: 'accept', class: "ui blue button" %>
          <%= f.submit "お断りする", name: 'refuse', class: "ui red button" %>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

<% if under_deal.work_status == 'refuse'%>
  <div class="ui stackable grid">
    <div class="wide column">
      <div class="ui success big message" style="text-align: center;">
        <h3>ドライバーからの申し込みをお断りしました。</h3>
      </div>
    </div>
  </div>
<% end %>

<% if under_deal.work_status == 'waiting_kit'%>
  <div class="ui stackable grid">
    <div class="wide column">
      <div class="ui success big message" style="text-align: center;">
        <h3>ドライバーへ広告キットを発送してください</h3>
      </div>
    </div>
  </div>
  <%= render 'under_deals/report_sponsor', under_deal: under_deal %>
<% end %>

<% if under_deal.work_status == 'sent_kit'%>
  <div class="ui stackable grid">
    <div class="wide column">
      <div class="ui success big message" style="text-align: center;">
        <h3>発送通知をしました!<br>ドライバーからの広告キット取り付け完了連絡をお待ちください。</h3>
      </div>
    </div>
  </div>
  <%= render 'under_deals/report_sponsor', under_deal: under_deal %>
<% end %>

<% if under_deal.work_status == 'advertising'%>
  <div class="ui stackable grid">
    <div class="wide column">
      <div class="ui success big message" style="text-align: center;">
        <h4>ドライバーから広告キット取付け完了の報告がきました。<br>これからドライバーが広告作業を行います。作業完了の報告をお待ちください。</h4>
      </div>
    </div>
  </div>
  <%= render 'under_deals/report_sponsor', under_deal: under_deal %>
<% end %>

<% if under_deal.work_status == 'completed'%>
  <div class="ui stackable grid">
    <div class="wide column">
      <div class="ui success big message" style="text-align: center;">
        <h3>広告作業が完了しました！</h3>
        <h4>広告作業代の振り込み作業を行ってください。お振込み完了後、評価をしてドライバーに報告をしてください。</h4>
      </div>
    </div>
  </div>
  <%= render 'under_deals/report_sponsor', under_deal: under_deal %>
<% end %>

<% if under_deal.work_status == 'transferred'%>
  <div class="ui stackable grid">
    <div class="wide column">
      <div class="ui success big message" style="text-align: center;">
        <h3>振り込み報告が完了しました！</h3>
        <h4>ドライバーからの受け取り連絡待ちです。</h4>
      </div>
    </div>
  </div>
  <%= render 'under_deals/report_sponsor', under_deal: under_deal %>
<% end %>

<% if under_deal.work_status == 'rated'%>
  <div class="ui stackable grid">
    <div class="wide column">
      <div class="ui success big message" style="text-align: center;">
        <h3>ドライバーから振り込み確認の連絡がきました！</h3>
        <h4>ドライバーの評価をして取引を終了させてください。</h4>
      </div>
    </div>
  </div>
  <%= render 'under_deals/report_sponsor', under_deal: under_deal %>
<% end %>

<% if under_deal.work_status == 'finished'%>
  <div class="ui stackable grid">
    <div class="wide column">
      <div class="ui success big message" style="text-align: center;">
        <h3>お疲れ様でした！</h3>
        <h4>お取引きが完了しました。宣伝したい広告はありませんか？</h4>
      </div>
    </div>
  </div>
  <%= render 'under_deals/report_sponsor', under_deal: under_deal %>
<% end %>

app/views/under_deals/_index_sponsor.html.erb
<div class="current-deal ui segment">
  <h3 class="ui header">取引中の広告一覧</h3>
  <table class="ui celled table">
    <thead>
      <tr>
        <th>広告名</th>
        <th>ドライバー</th>
        <th>広告期間</th>
        <th>ステータス</th>
        <th>詳細画面</th>
      </tr>
    </thead>
    <tbody>
      <% under_deals.each do |u| %>
        <tr>
          <td><%= u.advertisement.title %></td>
          <td><%= u.driver.name %></td>
          <td><%= u.advertisement.start_due_on %>〜<%= u.advertisement.end_due_on %></td>
          <td><%= u.work_status_i18n %></td>
          <td>
            <%= link_to under_deal_path(u.id), class: "ui green button" do %>
              詳細<i class="arrow right icon"></i>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
    
  <% if under_deals.blank? %>
    <div class="ui info message" style="text-align: center;">
      <h4>現在、取引中の広告はありません。<br>広告を依頼してみましょう！！</h4>
    </div>
  <% end %>

  <h3 class="ui header">過去の取引一覧</h3>
  <table class="ui celled table">
    <thead>
      <tr>
        <th>広告名</th>
        <th>ドライバー</th>
        <th>広告期間</th>
        <th>ステータス</th>
        <th>詳細画面</th>
      </tr>
    </thead>
    <tbody>
      <% finish_deals.each do |f| %>
        <tr>
          <td><%= f.advertisement.title %></td>
          <td><%= f.driver.name %></td>
          <td><%= f.advertisement.start_due_on %>〜<%= f.advertisement.end_due_on %></td>
          <td><%= f.work_status_i18n %></td>
          <td>
            <%= link_to under_deal_path(f.id), class: "ui green button" do %>
              詳細<i class="arrow right icon"></i>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/under_deals/_report_driver.html.erb
<div class="ui grid">
  <div class="column">
    <div id="report-area" class="ui segment">
      <p class="title ui header">やることリスト</p>

        <% if @under_deal.errors.any? %>
          <div class="ui error message">
            <div class="header">
              <%= @under_deal.errors.count %>件のエラーです。
            </div>
            <ul class="list">
              <% @under_deal.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>
      
      <div class="ui two column grid">
        
        <div class="column">
          <table class="ui table">
            <thead>
              <tr>
                <th><div class="text-center">広告取付け完了写真</div></th>
              </tr>
            </thead>
            <tbody>
              <tr>
								<td><% if under_deal.installation_image.attached? %>
									<div class="centered-image"><%= image_tag under_deal.installation_image.variant(resize_to_fill: [100, 100]) %></div>
								<% else %>
									<div class="centered-image"><%= image_tag "no_image.jpg", size: "160x120" %></div>
								<% end %></td>
              </tr>
            </tbody>
          </table>
        </div>

        <div class="column">
          <table class="ui table">
            <thead>
              <tr>
                <th><div class="text-center">広告キット設置報告</div></th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td>
                  <div class="centered-content">
                    <% if under_deal.work_status == 'sent_kit' %>
                      <%= form_with(model: under_deal, local: true, url: under_deal_path(under_deal), method: :patch) do |f| %>
                        <%= f.file_field :installation_image, id: :update_img %>
                        <label for="update_img" class="custom-file-label">ファイルを選択</label>
                        <br>
                        <%= f.submit "写真をアップロード", name:'advertising', class: "ui blue button" %>
                      <% end %>
                    <% else %>
                      <div class="ui disabled button" disabled>アップロード済み</div>
                    <% end %>
                  </div>
                </td>
              </tr>
            </tbody>
          </table>
        </div>

        <div class="column">
          <table class="ui table">
            <thead>
              <tr>
                <th><div class="text-center">作業完了報告</div></th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td>
                  <div class="centered-content">
                    <% if under_deal.work_status == 'advertising' %>
                      <% if driver.transfer_infos.blank? %>
                        <p class="ui warning message">口座情報が未登録です。「ドライバー情報 編集」から登録してください。</p>
                      <% else %>
                        <%= form_with model: under_deal, local: true, url: under_deal_path(under_deal), method: :patch do |f| %>
                          <%= f.label :transfer_infos, "振込先の銀行口座を指定する" %>
                          <%= collection_select(:detail, :transfer_info_id, driver.transfer_infos.order("id DESC"), :id, :full_info) %>
                          <%= f.submit "広告作業の完了報告", name:'completed', class: "ui blue button" %>
                        <% end %>
                      <% end %>
                    <% else %>
                      <div class="ui disabled button" disabled>作業の完了報告済み</div>
                    <% end %>
                  </div>
                </td>
              </tr>
            </tbody>
          </table>
        </div>

        <div class="column">
          <table class="ui table">
            <thead>
              <tr>
                <th><div class="text-center">評価</div></th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td>
                  <div class="centered-content">
                    <% if under_deal.work_status == 'transferred' %>
                      <%= form_with model: under_deal, local: true, url: under_deal_path(under_deal), method: :patch do |f| %>
                        <%= f.check_box :agreement, required: true, checked: false %>
                        <%= f.label :agreement, "入金を確認した" %><br>
                        <%= f.submit "スポンサーを評価", name:'rated', class: "ui blue button" %>
                      <% end %>
                    <% else %>
                      <div class="ui disabled button" disabled>評価済み</div>
                    <% end %>
                  </div>
                </td>
              </tr>
            </tbody>
          </table>
        </div>
      </div> 
    </div> 
  </div> 
</div>

app/views/under_deals/coming_soon.html.erb
<h2 class="text-center">こちらのページは只今準備中です。</h2>
<h3 class="text-center">ご迷惑をおかけして申し訳ございません<br>今しばらくお待ちくださいませ。</h3>

app/views/under_deals/show.html.erb
<div class="ui stackable grid">
  <div class="three wide column">
    <%= render 'sponsors/sidebar', sponsor: current_sponsor %>
  </div>
  <div class="twelve wide column">
  
    <div class="ui segment">
      <% if @under_deal.work_status == 'finished' %>
        <h4 class="ui dividing header">過去の取引</h4>
      <% else %>
        <h4 class="ui dividing header">取引中の広告</h4>
      <% end %>
      <%= render 'under_deals/advertisement_info', advertisement: @advertisement %>
      <%= render 'under_deals/flow_sponsor', under_deal: @under_deal %>


      <div class="ui segment">
				<h4 class="ui dividing header">メッセージ記録</h4>
				<% if @deal_messages.blank? %>
					<h4 class="ui warning message">メッセージはありません</h4>
				<% end %>

        <% @deal_messages.each do |message| %>
          <% if message.user_type == 'driver'  %>
            <div class="comment <%= message.user_type %>" style="text-align: right; display: flex; align-items: start; justify-content: flex-end;">
              <div class="content" style="display: flex; flex-direction: column; align-items: flex-end;">
                <div class="text <%= message.user_type %>">
                  <%= message.message %>
                </div>
                <div class="metadata">
                  <span class="date"><%= message.created_at.to_s(:datetime_jp) %></span>
                </div>
              </div>
              <div class="avatar" style="margin-left: 10px;">
                <%= image_tag @under_deal.driver.profile_image.variant(resize_to_fill: [50, 50]) %>
              </div>
            </div>
          <% else %>
            <div class="comment <%= message.user_type %>" style="display: flex;">
              <div class="avatar">
                <%= image_tag @under_deal.advertisement.sponsor.company_image.variant(resize_to_fill: [50, 50]) %>
              </div>
              <div class="content">
                <div class="text <%= message.user_type %>">
                  <%= message.message %>
                </div>
                <div class="metadata">
                  <span class="date"><%= message.created_at.to_s(:datetime_jp) %></span>
                </div>
              </div>
            </div>
          <% end %>
        <% end %>
      </div>
      
      <% if !['finished', 'checked_refuse'].include?(@under_deal.work_status) %>
        <div id="chat-templete">
          <%= form_with(model: @deal_message, local: true, url: under_deal_deal_messages_path(@under_deal)) do |f| %>
            <div class="flex-container">
              <%= f.text_area :message, placeholder: "メッセージを入力してください。", class: "chat-message flex-input" %>
              <%= f.submit "送信", class: "ui button chat-btn teal" %>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>