config/routes.rb
Rails.application.routes.draw do
  get 'health_check/index'
  devise_for :admins, controllers:{ 
    registrations: 'admins/registrations',
    sessions: 'admins/sessions' 
  }
  devise_scope :admin do
    post 'admin/guest_sign_in', to: 'admins/sessions#guest_sign_in'
  end

  devise_for :drivers, controllers:{ 
    registrations: 'drivers/registrations',
    sessions: 'drivers/sessions' 
  }
  devise_scope :driver do
    post 'driver/guest_sign_in', to: 'drivers/sessions#guest_sign_in'
  end

  devise_for :sponsors, controllers:{ 
    registrations: 'sponsors/registrations',
    sessions: 'sponsors/sessions' }
  devise_scope :sponsor do
    post 'sponsor/guest_sign_in', to: 'sponsors/sessions#guest_sign_in'
  end

  root 'homes#index'
  resources :homes, only: %i[ index ] do
    collection do
      get :about
    end
  end

  resources :drivers, only: %i[ index show edit update ] do
    member do
      get :dashboard
      get :followings, :followers
    end
    resources :car_infos, only: %i[ index create edit update destroy ]
    resources :transfer_infos, only: %i[ index create edit update destroy ]
  end

  resources :sponsors, only: %i[ index show edit update ] do
    member do
      get :dashboard
      get :followings, :followers
    end
    scope module: :sponsors do
      resources :advertisements
    end
  end

  resources :under_deals, only: %i[ index show create edit update ] do
    member do
      get :show_driver
    end
    resources :deal_messages, only: %i[ create ]
  end
  scope module: :under_deals do
      get :coming_soon
	end

  resources :infos

  resources :admins, only: %i[ index ]
    namespace :admins do
      resources :sponsors, only: %i[ index show update ]
      resources :drivers, only: %i[ index show update ]
      resources :genres, only: %i[ index create edit update destroy ]
      resources :contacts, only: %i[ index show ]
    end

  resources :contacts, only: %i[ index new create show update ] do
    collection do
      post :confirm
    end
  end
  scope module: :contacts do
    get :new_inquiry
    get :working_inquiry
    get :past_inquiry
  end

  resources :advertisements, only: %i[ index show ] do
    resources :chats, only: %i[ index create ]
    resources :rooms, only: %i[ index show create ]
    member do
      get :genre_index
      get :favorite_index
    end
    resource :favorites, only: %i[ create destroy ]
  end

  post 'relationship_drivers/:sponsor_id', to: 'relationship_drivers#create', as:'relationship_drivers'
  delete 'relationship_drivers/:sponsor_id', to: 'relationship_drivers#destroy'
  
  post '/relationships/:driver_id',to: 'relationships#create',as:'relationships'
  delete '/relationships/:driver_id',to: 'relationships#destroy'
end

app/models/car_info.rb
class CarInfo < ApplicationRecord
  validates :manufacturer_name, presence: true
  validates :name, presence: true
  validates :flame_number, presence: true
  validates :license_plate, presence: true
  validates :vehicle_image, presence: true, blob: { content_type: :image }

  belongs_to :driver
  has_one_attached :vehicle_image
end

app/controllers/car_infos_controller.rb
class CarInfosController < ApplicationController
  before_action :authenticate_driver!
  before_action :set_car_info, only: %i[ edit update destroy ]

  def index
    @car_info = CarInfo.new
    @car_infos = current_driver.car_infos
  end

  def edit 
  end

  def create
    @car_info = current_driver.car_infos.build(car_info_params)
    if @car_info.save
      redirect_to driver_car_infos_path(current_driver)
    else
      render :index
    end
  end

  def update
    if @car_info.update(car_info_params)
      redirect_to driver_car_infos_path(current_driver)
    else
      render :edit
    end
  end

  def destroy
    @car_info.destroy
    redirect_to driver_car_infos_path(current_driver)
  end

  private

  def set_car_info
    @car_info = current_driver.car_infos.find(params[:id])
  end

  def car_info_params
    params.require(:car_info).permit(:manufacturer_name, :name, :flame_number, :license_plate, :vehicle_image)
  end
end

app/views/car_infos/edit.html.erb
<div class="ui container">
  <h3 class="ui dividing header">登録車両編集</h3>
  
  <% if @car_info.errors.any? %>
  <div class="ui negative message">
    <div class="header">
      <%= @car_info.errors.count %>件のエラーです
    </div>
    <ul class="list">
      <% @car_info.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
  <% end %>

  <div class="ui segment">
    <%= form_with(model: @car_info, local: true, url: driver_car_info_path, class: "ui form") do |f| %>
      <div class="field">
        <%= f.label :manufacturer_name, class: "ui label" %>
        <%= f.text_field :manufacturer_name, autofocus: true, placeholder: "車のメーカー名を入力" %>
      </div>

      <div class="field">
        <%= f.label :name, class: "ui label" %>
        <%= f.text_field :name, autofocus: true, placeholder: "車種名を入力" %>
      </div> 

      <div class="field">
        <%= f.label :flame_number, class: "ui label" %>
        <%= f.text_field :flame_number, autofocus: true, placeholder: "車両検査表に記載の車台番号を入力" %>
      </div>

      <div class="field">
        <%= f.label :license_plate, class: "ui label" %>
        <%= f.text_field :license_plate, autofocus: true, placeholder: "登録番号を入力" %>
      </div>

      <div class="field">
        <%= f.label :vehicle_image, class: "ui label" %>
        <%= f.file_field :vehicle_image %>
        <%= image_tag @car_info.vehicle_image.variant(resize_to_fill: [200, 200]) if @car_info.vehicle_image.attached? %>
      </div>

      <%= f.submit "登 録", class: "ui fluid primary button" %>
    <% end %>
  </div>
  <%= link_to "前の画面に戻る", driver_car_infos_path(current_driver), class: "fas fa-angle-left" %>
</div>

app/views/car_infos/index.html.erb
<h3 class="ui dividing header">新規車両登録</h3>

<% if @car_info.errors.any? %>
  <div class="ui negative message">
    <div class="header">
      <%= @car_info.errors.count %>件のエラーです
    </div>
    <ul class="list">
      <% @car_info.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<div class="ui segment">
  <%= form_with(model: @car_info, local: true, url: driver_car_infos_path, class: "ui form", html: { autocomplete: "off"}) do |f| %>
    <div class="field">
      <%= f.label :manufacturer_name, class: "ui label" %>
      <%= f.text_field :manufacturer_name, autofocus: true, placeholder: "車のメーカー名を入力" %>
    </div>

    <div class="field">
      <%= f.label :name, class: "ui label" %>
      <%= f.text_field :name, autofocus: true, placeholder: "車種名を入力" %>
    </div> 

    <div class="field">
      <%= f.label :flame_number, class: "ui label" %>
      <%= f.text_field :flame_number, autofocus: true, placeholder: "車両検査表に記載の車台番号を入力" %>
    </div>

    <div class="field">
      <%= f.label :license_plate, class: "ui label" %>
      <%= f.text_field :license_plate, autofocus: true, placeholder: "登録番号を入力" %>
    </div>

    <div class="field">
      <%= f.label :vehicle_image, class: "ui label" %>
      <%= f.file_field :vehicle_image %>
    </div>

    <%= f.submit "登 録", class: "ui fluid primary button" %>
  <% end %>
</div>

<div class="ui segment">
  <h3>登録車両一覧</h3>
  <table class="ui celled table">
    <thead>
      <tr>
        <th>メーカー名</th>
        <th>車名</th>
        <th>ナンバープレート</th>
        <th>車台番号</th>
        <th>車検証写真</th>
        <th></th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @car_infos.each do |car_info| %>
        <tr>
          <td><%= car_info.manufacturer_name %></td>
          <td><%= car_info.name %></td>
          <td><%= car_info.flame_number %></td>
          <td><%= car_info.license_plate %></td>
          <td><%= image_tag car_info.vehicle_image.variant(resize_to_fill: [100, 100]) %></td>
          <td>
            <%= link_to "編 集", edit_driver_car_info_path(car_info.driver_id, car_info.id), class: "ui green button" %>
          </td>
          <td>
            <%= link_to "削 除", driver_car_info_path(car_info.driver_id, car_info.id), method: :delete, data: { confirm: "本当に削除してもよろしいですか？" }, class: "ui button negative" %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

  <%= link_to "前の画面に戻る", dashboard_driver_path(current_driver), class: "fas fa-angle-left" %>